steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--build-arg'
      - 'DB_USER=$_DB_USER'
      - '--build-arg'
      - 'DB_PASSWORD=$_DB_PASSWORD'
      - '--build-arg'
      - 'DB_HOST=$_DB_HOST'
      - '--build-arg'
      - 'DB_PORT=$_DB_PORT'
      - '--build-arg'
      - 'DB_DATABASE=$_DB_DATABASE'
      - '--build-arg'
      - 'HASURA_ADMIN_SECRET=$_HASURA_ADMIN_SECRET'
      - '--build-arg'
      - 'HASURA_GRAPHQL_UNAUTHORIZED_ROLE=$_HASURA_GRAPHQL_UNAUTHORIZED_ROLE'
      - '--no-cache'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _LABELS: gcb-trigger-id=a77f8900-a6c9-45b3-8cff-0a09eee40bc2
  _TRIGGER_ID: a77f8900-a6c9-45b3-8cff-0a09eee40bc2
  _SERVICE_NAME: memo-app-sample-hasura
  _DEPLOY_REGION: asia-northeast1
  _GCR_HOSTNAME: asia.gcr.io
  _PLATFORM: managed
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - memo-app-sample-hasura
